title: "JCNay Vida Team"
description: "Protección Financiera Editorial"
baseurl: "/jcnay-vida-team"
url: "https://jcynay0206.github.io"

markdown: kramdown
theme: minima

plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/blog/page:num/"
