title: "JCNay Vida Team"
description: "Protección Financiera Editorial"

baseurl: "/jcnay-vida-team"
url: "https://jcnay0206.github.io"

markdown: kramdown

plugins:
  - jekyll-paginate

collections:
  posts:
    output: true

paginate: 10
paginate_path: "/blog/page:num/"

future: true
timezone: America/New_York
